In [ ]:
import pandas as pd

In [ ]:
import sklearn as skl

In [ ]:
dataframe = pd.read_csv('/content/Stars.csv')

In [ ]:
dataframe

Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]

In [ ]:
dataset = dataframe.drop("Type", axis=1)
label = dataframe["Type"].copy()

Separamos los datos

In [ ]:
dataset

Temperature              L          R    A_M  Color Spectral_Class
0           3068       0.002400     0.1700  16.12    Red              M
1           3042       0.000500     0.1542  16.60    Red              M
2           2600       0.000300     0.1020  18.70    Red              M
3           2800       0.000200     0.1600  16.65    Red              M
4           1939       0.000138     0.1030  20.06    Red              M
..           ...            ...        ...    ...    ...            ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O
236        30839  834042.000000  1194.0000 -10.63   Blue              O
237         8829  537493.000000  1423.0000 -10.73  White              A
238         9235  404940.000000  1112.0000 -11.23  White              A
239        37882  294903.000000  1783.0000  -7.80   Blue              O

[240 rows x 6 columns]

In [ ]:
label

0      0
1      0
2      0
3      0
4      0
      ..
235    5
236    5
237    5
238    5
239    5
Name: Type, Length: 240, dtype: int64

In [ ]:
label.to_frame()

Type
0       0
1       0
2       0
3       0
4       0
..    ...
235     5
236     5
237     5
238     5
239     5

[240 rows x 1 columns]

In [ ]:
dataset.shape

(240, 6)

In [ ]:
label.shape

(240,)

In [ ]:
mean_temp = dataframe["Temperature"].mean()
dataframe_op3 = dataframe["Temperature"].fillna(mean_temp)  #

In [ ]:
#Llenamos los NaN con el valor medio

In [ ]:
dataset.isnull().sum()

Temperature       0
L                 0
R                 0
A_M               0
Color             0
Spectral_Class    0
dtype: int64

In [ ]:
dataframe.isnull().sum()

Temperature       0
L                 0
R                 0
A_M               0
Color             0
Spectral_Class    0
Type              0
dtype: int64

Conversión de datos

In [ ]:
color_cat = dataframe[['Color']]
spectral_cat = dataframe[['Spectral_Class']]
print(color_cat.head(10))
print(spectral_cat.head(10))

  Color
0   Red
1   Red
2   Red
3   Red
4   Red
5   Red
6   Red
7   Red
8   Red
9   Red
  Spectral_Class
0              M
1              M
2              M
3              M
4              M
5              M
6              M
7              M
8              M
9              M


Conversión OrdinalEnconder (Se usa cuando hay proximidad, ej Malo=0, Intermedio=1, Bueno=2 
En este dataframe los colores no tienen proximidad, no se recomienda hacerlo

In [ ]:
dataset2 = dataset.copy()

In [ ]:
dataset2

Temperature              L          R    A_M  Color Spectral_Class
0           3068       0.002400     0.1700  16.12    Red              M
1           3042       0.000500     0.1542  16.60    Red              M
2           2600       0.000300     0.1020  18.70    Red              M
3           2800       0.000200     0.1600  16.65    Red              M
4           1939       0.000138     0.1030  20.06    Red              M
..           ...            ...        ...    ...    ...            ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O
236        30839  834042.000000  1194.0000 -10.63   Blue              O
237         8829  537493.000000  1423.0000 -10.73  White              A
238         9235  404940.000000  1112.0000 -11.23  White              A
239        37882  294903.000000  1783.0000  -7.80   Blue              O

[240 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
color_cat_encoded = ordinal_encoder.fit_transform(color_cat)
print(color_cat_encoded[:40])

[[ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 1.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 1.]
 [13.]
 [ 2.]
 [13.]
 [13.]
 [ 7.]
 [ 0.]
 [ 4.]
 [ 4.]
 [11.]
 [15.]
 [11.]
 [15.]
 [15.]
 [15.]
 [15.]]


In [ ]:
lalala = dataframe['Color'].head(40)

In [ ]:
lalala

0                    Red
1                    Red
2                    Red
3                    Red
4                    Red
5                    Red
6                    Red
7                    Red
8                    Red
9                    Red
10                   Red
11                   Red
12                   Red
13                   Red
14                   Red
15                   Red
16                   Red
17                   Red
18                   Red
19                   Red
20            Blue White
21                 White
22                 White
23                 White
24            Blue White
25       Yellowish White
26            Blue white
27       Yellowish White
28       Yellowish White
29    Pale yellow orange
30                  Blue
31            Blue-white
32            Blue-white
33               Whitish
34          yellow-white
35               Whitish
36          yellow-white
37          yellow-white
38          yellow-white
39          yellow-white


Conversión OneHotEncoder, para cuando no hay proximidad

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
color_cat_one_hot = one_hot_encoder.fit_transform(color_cat)
print(color_cat_one_hot.toarray().shape)
print(color_cat_one_hot.toarray())

(240, 17)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


Homogenización de datos

Normalización

In [ ]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
l_values = dataframe[['L']]
scaled_values = min_max_scaler.fit(l_values)
print(min_max_scaler.transform(l_values)[0:10])

[[2.73127546e-09]
 [4.94455040e-10]
 [2.59000259e-10]
 [1.41272869e-10]
 [6.82818865e-11]
 [6.71046126e-10]
 [7.65228038e-10]
 [3.76727649e-10]
 [7.18137082e-10]
 [1.17727390e-10]]


Estandarización de datos

In [ ]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
l_values = dataframe[['L']]
scaled_values = standard_scaler.fit(l_values)
print(standard_scaler.transform(l_values)[0:10])

[[-0.59862356]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]
 [-0.59862357]]


Pipelines = automatización del preprocesamiento

In [ ]:
from sklearn.compose import ColumnTransformer
num_attrs = ["Temperature", "L", "R"]
text_attrs = ["Color", "Spectral_Class"]

pipeline = ColumnTransformer([
                              ("numeric", StandardScaler(), num_attrs),
                              ("text", OneHotEncoder(), text_attrs)
])
preprocessed_dataset = pipeline.fit_transform(dataset)

In [ ]:
preprocessed_dataset

<240x27 sparse matrix of type '<class 'numpy.float64'>'
	with 1200 stored elements in Compressed Sparse Row format>

In [ ]:
aG = preprocessed_dataset

Fin del preprocesamiento

Usar los datos

In [ ]:
preprocessed_dataset

<240x27 sparse matrix of type '<class 'numpy.float64'>'
	with 1200 stored elements in Compressed Sparse Row format>

Partición del dataframe

In [ ]:
from sklearn.model_selection import train_test_split
#Partición del dataset en un conjunto de entrenamiento y otro de test (20%)
X_train, X_test, y_train, y_test = train_test_split(preprocessed_dataset, label, test_size=0.2, random_state=42)

Ver el Accuracy de distintos modelos

In [ ]:
from sklearn.svm import SVC

# Creación
classifier =  SVC()

# Entrenamiento
classifier.fit(X_train, y_train)

# Accuracy de nuestro modelo para el conjunto de test
print(classifier.score(X_test, y_test))

0.8333333333333334


Cross validation

In [ ]:
from sklearn.model_selection import train_test_split

# Renombramos los valores para que X sean los atributos e Y sean las respuestas del sistema
X = dataset.Color
y = dataset.Spectral_Class

# Realizamos la partición de nuestro dataset en un conjunto de entrenamiento y otro de test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.model_selection import cross_val_score
nScores = cross_val_score(classifier, X, y, cv=10)
# Nos devuelve un array de tipo Numpy. Podemos usar el método mean para obtener la media de los valores devueltos
nScores.mean()

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
10 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py", line 196, in fit
    accept_large_sparse=False,
  File "/us

nan

Librerías de sklearn usadas:
OrdinalEncoder
OneHotEncoder

MinMaxScaler

StandardScaler

ColumnTransformer

Train_test_split
cross_val_score